version: "3.9"
services: 
  api:
    build: .
    ports:
      - "5000:5000"
    volumes: 
      - .:/inet-trouble-ml-api
    networks:
      - inet-trouble-ml-api

networks: 
  inet-trouble-ml-api:
    driver: bridge
